version: "3"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  webserver:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: your_super_secret_key_here
      AIRFLOW__WEBSERVER__BASE_URL: http://webserver:8080      
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: >
      bash -c "
        pip install requests &&
        airflow db init &&
        airflow users create --username airflow --firstname Air --lastname Flow --role Admin --email airflow@example.com --password airflow &&
        airflow webserver
      "

  scheduler:
    image: apache/airflow:2.8.1
    depends_on:
      - webserver
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: your_super_secret_key_here
    volumes:
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "
        pip install requests &&
        sleep 10 &&
        airflow scheduler
      "

volumes:
  postgres_data:
