name: Deploy DAG to Airflow (Local)

on:
  push:
    paths:
      - 'dags/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy DAGs to airflow container
        run: |
          echo "📂 Copying DAGs to airflow-webserver..."
          docker cp dags/. airflow-webserver:/opt/airflow/dags/
          echo "♻️ Restarting scheduler..."
          docker restart airflow-scheduler || docker restart scheduler
